DROP TABLE IF EXISTS pointsmaps CASCADE;
CREATE TABLE pointsmaps (
  id SERIAL PRIMARY KEY NOT NULL,
  point_id INTEGER REFERENCES points(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE
);
